# Generated by Django 5.0.3 on 2024-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('electronique', 'Electronique'), ('vetement', 'Vetement'), ('cosmetique', 'Cosmetique')], max_length=25, null=True)),
                ('quantite', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
