# Generated by Django 5.0.3 on 2024-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_produit_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
