# Generated by Django 5.0.3 on 2024-04-09 13:20

import dashboard.middleware
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_produit_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='personnel',
            field=models.ForeignKey(default=dashboard.middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('montant_total', models.PositiveIntegerField(default=0)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.produit')),
            ],
            options={
                'verbose_name_plural': 'Ventes',
            },
        ),
    ]
