# Generated by Django 5.0.3 on 2024-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
