# Generated by Django 5.0.3 on 2024-05-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ('date_vente',), 'verbose_name_plural': 'Ventes'},
        ),
    ]
