# Generated by Django 5.0.3 on 2024-05-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_vente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
